#!/bin/bash
set -e

# Create sync user
MASTER_SYNC_USER=${MASTER_SYNC_USER}
MASTER_SYNC_PASSWORD=${MASTER_SYNC_PASSWORD}
ROOT_USER="root"
ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
SYNC_ALLOW_HOST=${SYNC_ALLOW_HOST}
CREATE_SYNC_USER_SQL="CREATE USER '$MASTER_SYNC_USER'@'$SYNC_ALLOW_HOST' IDENTIFIED WITH mysql_native_password BY '$MASTER_SYNC_PASSWORD';"
GRANT_SYNC_PRIVILEGES_SQL="GRANT REPLICATION SLAVE,REPLICATION CLIENT ON *.* TO '$MASTER_SYNC_USER'@'$SYNC_ALLOW_HOST';"
FLUSH_SYNC_PRIVILEGES_SQL="FLUSH PRIVILEGES;"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$CREATE_SYNC_USER_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$GRANT_SYNC_PRIVILEGES_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$FLUSH_SYNC_PRIVILEGES_SQL"

# Create read and write user
R_W_USER=${R_W_USER}
R_W_USER_PASSWORD=${R_W_USER_PASSWORD}
R_W_USER_HOST=${R_W_USER_HOST}
R_W_DATABASE=${R_W_DATABASE}
CREATE_RW_USER_SQL="CREATE USER '$R_W_USER'@'$R_W_USER_HOST' IDENTIFIED WITH mysql_native_password BY '$R_W_USER_PASSWORD';"
GRANT_RW_PRIVILEGES_SQL="GRANT XA_RECOVER_ADMIN,CREATE,DROP,INSERT,UPDATE,DELETE,SELECT ON $R_W_DATABASE.* TO '$R_W_USER'@'$R_W_USER_HOST';"
FLUSH_RW_PRIVILEGES_SQL="FLUSH PRIVILEGES;"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$CREATE_RW_USER_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$GRANT_RW_PRIVILEGES_SQL"
mysql -u"$ROOT_USER" -p"$ROOT_PASSWORD" -e "$FLUSH_RW_PRIVILEGES_SQL"
